-- CREATE TABLE youtubers(
--    Country      VARCHAR(32) NOT NULL PRIMARY KEY,
--   ,YoutuberName VARCHAR(48) NOT NULL
--   ,ContentType  VARCHAR(14) NOT NULL
-- );


INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Iceland','Sorelle Amore','Entertainment');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Bahamas','Crypto Beadles','Tech');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Cyprus','TumkaGames / Тумка:3','Gaming');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Mozambique','Arte e Vida','Entertainment');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Tanzania','Young Tubers','Kids');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Libya','King GTA','Gaming');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Ethiopia','Amharic Cooking','How To');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Botswana','Shree craft place','How To');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Nauru','JerseySurvivor','Entertainment');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Tonga','TasteoftheSouthPacific','How To');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Japan','はじめしゃちょー（hajime）','Entertainment');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Vietnam','NTN Vlogs','Entertainment');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Sweden','Narins Beauty','Beauty & Style');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Serbia','Life Hacks & Experiments','How To');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Micronesia, Federated States of','dxd101','Entertainment');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Jamaica','Yanrique','Gaming');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Guyana','Pro Marathi','Tech');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Palestine','Fozi Mozi','Kids');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Italy','Marzia','Entertainment');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Algeria','Oum Walid','How To');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Timor Leste','king_vieira OFFICIAL','Music');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Iraq','قناة منوعات الكوميدية العراقيه','People & Blogs');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Azerbaijan','Resul Abbasov Official','Entertainment');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Montenegro','AdnanBro','Gaming');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Seychelles','Rosa Gruner','Gaming');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Guinea-Bissau','Editing ki Dukan','How To');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Romania','Be Inspired','Education');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Nigeria','MarkAngelComedy','Comedy');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Panama','Mimonona Stories','Kids');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Laos','Bigyai Seehalad','Entertainment');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Barbados','Brilliant News','Entertainment');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Bhutan','Cigano Ramires','People & Blogs');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('United States of America','Like Nastya','Kids');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Belize','ngashigi kangleipak','People & Blogs');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Djibouti','Eman Lotfi','Entertainment');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Cuba','Lifeples','Entertainment');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Brunei','Bernardo Werneck','Entertainment');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('San Marino','BlackJack997','Autos');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Mongolia','Mesmerism Official','Comedy');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Finland','TheRelaxingEnd','Gaming');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Andorra','Tri-line','Entertainment');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Uruguay','Dosogas','Entertainment');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Egypt','Ahmed Hassan Family','Entertainment');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Singapore','মায়াজাল','Entertainment');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('New Zealand','Rainbow Learning','Kids');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Georgia','Guka Family Show','Kids');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Kuwait','AboFlah','Gaming');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Portugal','SirKazzio','Entertainment');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Austria','Fabio Wibmer','Sports');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Saint Vincent and the Grenadines','The Motivator 2','Sports');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Madagascar','Philippe MARRONE','Sports');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Solomon Islands','Caroline Elizabeth','Entertainment');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Ghana','RakGhana','Comedy');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Malawi','Dj Àmit Áligarh','Music');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Mexico','Badabun','Entertainment');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Benin','Ma Chaîne','How To');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Chile','HolaSoyGerman','Entertainment');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Israel','Jamal alimwase ـ جمال العمواسي','Nature');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Wales','Ben Phillips','Entertainment');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Malaysia','PlataBush','Gaming');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Bangladesh','Farjana Drawing Academy','How To');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Poland','Blowek','Entertainment');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Morocco','YassPlays','Gaming');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Slovenia','TimKo Kid','Kids');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Venezuela','KeiferMC','Gaming');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Dominican Republic','ElFlacoWTF','Entertainment');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Belgium','Akosi Dogie','Entertainment');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Sudan','المنهج السلفي بالسودان','People & Blogs');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Brazil','whinderssonnunes','Comedy');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Somalia','Balanbaalis Studio','Music');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Namibia','Namiban gospel music','Entertainment');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Burkina Faso','Jackson Oliveira','Entertainment');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Spain','elrubiusOMG','Entertainment');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Sierra Leone','BlackPearl','How To');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('El Salvador','Fernanfloo','Gaming');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Zimbabwe','King Gryph','Gaming');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Saint Kitts and Nevis','Dr.Mungli','Education');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Kenya','Henry DeSagu','Entertainment');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Togo','Fortnite Fantasy','Gaming');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Tuvalu','GuruKidHD','Gaming');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Turkmenistan','Ned Tocino','Entertainment');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Macau','籽岷','Gaming');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Guinea','Faits - Divers GUINEE','News');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Denmark','SYBO TV','Gaming');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Tunisia','Born2Kill','Gaming');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Bahrain','عمر فاروق Omar Farooq','Entertainment');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Albania','Co Vines','Entertainment');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Pakistan','Kitchen with Amna','How To');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Palau','Ananda Kelly','How To');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Taiwan','TGOP (This Group Of People)','Entertainment');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Jordan','Rozzah','Entertainment');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Estonia','Life of Boris','Entertainment');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Switzerland','LE GRAND JD','Entertainment');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Cameroon','BYSNESS Comédie Club','Comedy');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Saint Lucia','The Dating Guru','How To');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Liechtenstein','caracol3000','News');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('North Korea','Making ASMR','How To');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Sao Tome and Principe','Anrita Melchizedek','Education');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Canada','VanossGaming','Gaming');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Trinidad and Tobago','Certified sampson','Comedy');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Ireland (Republic of)','jacksepticeye','Gaming');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Indonesia','Atta Halilintar','Entertainment');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Congo (Republic of the)','ASTUCES NATURELLES - DR KOLO','Education');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Dominica','Chanel Raphael.','People & Blogs');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Grenada','Laura Forde','How To');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Uzbekistan','Jasur Hamroyev','People & Blogs');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('India','CarryMinati','Comedy');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('United Arab Emirates','shfa','Kids');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Tajikistan','Shava TuBe','People & Blogs');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Luxembourg','LuxGamer','Gaming');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Afghanistan','Tech Zaada','Tech');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Cape Verde','Fred walkthrough','Gaming');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Chad','twifacetube','Entertainment');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Belarus','A4','Entertainment');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Ireland (Northern)','Adam B','People & Blogs');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Yemen','صدام العزي','Entertainment');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Czech Republic','ViralBrothers','Entertainment');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Liberia','مهووس عضلات/كمال الاجسام','How To');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Slovakia','Peter PlutaX','How To');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Malta','Grandayy','Entertainment');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Nicaragua','JR INN','Comedy');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Hong Kong','Emi Wong','People & Blogs');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Scotland','Mike Boyd','Entertainment');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Moldova','GurinelTV','Kids');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Greece','KM Music','Entertainment');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Paraguay','TÍO RICZER','Entertainment');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Lithuania','Maria OMG','Entertainment');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Oman','قرية العجائب','Entertainment');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Lebanon','Laila Mourad','Entertainment');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Bulgaria','Bodil40','Gaming');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Comoros','Vallenatos En Vivo Oficial','Entertainment');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Haiti','Komedyen Lakay Official','Comedy');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Angola','ShiryuAmigo龍','Comedy');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Mali','MS2A FUNNY','Comedy');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Central African Republic','THE TRUE ROYAL FAMILY','Education');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Argentina','DrossRotzank','Entertainment');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Germany','HaerteTest','Entertainment');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Mauritius','Ikhlaas MJ','Entertainment');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Saudi Arabia','mmoshaya','Entertainment');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Ukraine','SlivkiShow','Entertainment');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Burundi','Gasore Ismael Comedien','Comedy');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Australia','CKN Toys','Kids');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Suriname','SRJ Musik','Music');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('France','SQUEEZIE','Entertainment');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Iran','KhanAga Alireza Alibabaei Jabbari','Entertainment');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Russia','TheBrianMaps','Entertainment');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('South Korea','Boram Tube ToysReview [보람튜브 토이리뷰]','Kids');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Thailand','Kaykai Salaider','Entertainment');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Netherlands','NikkieTutorials','Beauty & Style');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Peru','Shidory Drawblogs','Entertainment');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Turkey','Enes Batur','Entertainment');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Philippines','Ranz Kyle','Entertainment');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Myanmar','khunThinmg pao','Comedy');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Gabon','Xavier HUBERT-BRIERRE','Nature');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Colombia','Ami Rodriguez','Entertainment');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('The Gambia','ebrohaugh','People & Blogs');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('China','李子柒 Liziqi','How To');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Rwanda','Shangazi Emma-Claudine','People & Blogs');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('England','PewDiePie','Entertainment');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Mauritania','INFOS AABD','Tech');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Norway','SaraBeautyCorner - DIY, Comedy, Makeup, Nail Art','Beauty & Style');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Ecuador','Doc Tops','Entertainment');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Kiribati','TV WULKAN - లొఽథటలలొప్రఠఽరగల్వ','Entertainment');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Lesotho','Omnia Stars','How To');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Hungary','R3D 1','Entertainment');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Cambodia','fanKID','Entertainment');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Latvia','Little Movies Games & Fun','Gaming');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Nepal','Tattato Khabar','News');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Guatemala','Jexs','Comedy');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('South Africa','morecaspar','Entertainment');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Cote d’Ivoire (Ivory Coast)','video whatsapptube','Entertainment');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Costa Rica','Germán Rodezel','Entertainment');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Bolivia','Edson FDB','Gaming');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Qatar','Kareemtime Official','Comedy');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Bosnia and Herzegovina','Omco','Comedy');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Monaco','Jon Olsson','People & Blogs');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Zambia','Cartoon Club','Kids');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Sri Lanka','Apé Amma','People & Blogs');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Armenia','Arin أرين','Entertainment');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Kazakhstan','Ekaterina Saibel','People & Blogs');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Honduras','músicos Cínicos 鯉','Music');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Croatia','Doctor DS','Autos');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Senegal','Hussein and Zeinab.','Kids');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Uganda','Masaka Kids Afrikana','Kids');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Kyrgyzstan','Сань Янь','Kids');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Syria','OtakuGamer - أوتاكو قيمر','Gaming');
INSERT INTO youtubers(Country,YoutuberName,ContentType) VALUES ('Swaziland (Eswatini)','OuSSama MiZani','Entertainment');
