"""me

Revision ID: 1f908a8ded75
Revises: 
Create Date: 2022-04-10 14:12:43.907814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f908a8ded75'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('youtubers_ContentType_key', 'youtubers', type_='unique')
    op.drop_constraint('youtubers_YoutuberName_key', 'youtubers', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('youtubers_YoutuberName_key', 'youtubers', ['YoutuberName'])
    op.create_unique_constraint('youtubers_ContentType_key', 'youtubers', ['ContentType'])
    # ### end Alembic commands ###
